### ISSUE TITLE
SE clean makes lots of changes, particularly to .svg files

### ISSUE THREAD

**Issue by drgrigg** [robinwhittleton/beatrix-potter_short-fiction#2]
I imagine this is due to the recent optimisation of the SVGs.

**Comment by robinwhittleton** [comment]
Those were all reasonable changes, I just haven’t run clean in a while 😅 Fixed in https://github.com/robinwhittleton/beatrix-potter_short-fiction/commit/a53781f5a78451457efa04c7d1ffd375c920e83a.
