### ISSUE TITLE
Some <em> tags should be <i>

### ISSUE THREAD

**Issue by drgrigg** [robinwhittleton/beatrix-potter_short-fiction#3]
In "The Tailor of Gloucester", I would have thought that `<em>Tip tap, tip tap, tip tap tip!</em>` should be classed as onomatopoeia and thus given `<i>` tags. 

I also find the italicisation of certain words in "The Tale of Squirrel Nutkin" rather odd, but they are in the page scans so I guess we just leave them: 

`a little red <em>cherry</em>`, `They had stolen it out of a bumble <em>bees’</em> nest` etc.

**Comment by robinwhittleton** [comment]
Fixed Gloucester in https://github.com/robinwhittleton/beatrix-potter_short-fiction/commit/878bb40ffb8954794e02b9845c87f25813b5c53c.

Agreed to leave Nutkin as is.
