### ISSUE TITLE
Typo in long description

### ISSUE THREAD

**Issue by drgrigg** [robinwhittleton/beatrix-potter_short-fiction#5]
"fungii" has one two many "i" s. 

Personally, I would prefer to see "funguses" because we speak English, not Latin, but that's a personal hobby-horse!!

**Comment by robinwhittleton** [comment]
Fixed in https://github.com/robinwhittleton/beatrix-potter_short-fiction/commit/a21468da5352a900bef27d236a3969336081f94d. Sorry, going with “fungi”, as the context is scientific drawings. Would have been tempted if it was The Tale of Mr. Mushroom.
