### ISSUE TITLE
Sectioning

### ISSUE THREAD

**Issue by acabal** [robinwhittleton/beatrix-potter_short-fiction#7]
I think we need to look at how dedications are sectioned. Typically in a book they're their own `<section>` and I think they should be here too. Also dedications are not blockquotes - they are not quotations. Most dedications are just `<p>`.

So what we should do is section most stories in this way:

```
<article id="the-tale-of-two-bad-mice">
    <header/>
    <section epub:type="dedication"/>
    <section id="the-tale-of-two-bad-mice-1">
        ... story body ...
````

We get a kind of crappy ID on the story body but I think the sectioning is a lot more natural. That way you can style the dedication with copy and paste from the manual and blockquotes aren't necessary as a wrapper.

For The Tailor of Gloucester we should follow the same concept, except no wrapping intro section; rather add a `<header>` including the frontispiece and epigraph, then a section for the dedication, and a section for the text body.

**Comment by acabal** [comment]
Modernize-spelling makes a few changes. I see one is a name which we should reject, but what about the rest?

**Comment by robinwhittleton** [comment]
I’m only seeing `Cross-patch` to `Crosspatch` as a suggestion, which I’ve ignored as it’s a name. Not seeing anything else?

I’ll check the dedications. Thanks for the review 🙂

**Comment by acabal** [comment]
The dev build also finds `knick-knack` and `mouse-trap`

**Comment by robinwhittleton** [comment]
I fixed those in https://github.com/robinwhittleton/beatrix-potter_short-fiction/commit/e5d0acc02e0118f23037dc2268890236b6720965. Pull again?

**Comment by acabal** [comment]
Ah, OK!

**Comment by robinwhittleton** [comment]
Right, fixed in https://github.com/robinwhittleton/beatrix-potter_short-fiction/commit/0cc9255210188f22a33b8f97e8a31739aa393307.
